### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by vbabenkoru** [cockroachlabs-field/cockroachdb-remote-client#9]
I'm getting this when launching the container:
```java.lang.IllegalStateException: Failed to execute ApplicationRunner

at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:785) ~[spring-boot-2.5.2.jar:2.5.2]

at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:772) ~[spring-boot-2.5.2.jar:2.5.2]

at org.springframework.boot.SpringApplication.run(SpringApplication.java:345) ~[spring-boot-2.5.2.jar:2.5.2]

at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.2.jar:2.5.2]

at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[spring-boot-2.5.2.jar:2.5.2]

at io.crdb.docker.RemoteClientApplication.main(RemoteClientApplication.java:36) ~[classes/:21.0.0-SNAPSHOT]

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[na:na]

at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]

at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]

at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[file:/:na]

at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[file:/:na]

at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[file:/:na]

at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[file:/:na]

Caused by: java.io.IOException: Cannot run program "/cockroach": error=0, Failed to exec spawn helper: pid: 29, exit value: 1

at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142) ~[na:na]

at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073) ~[na:na]

at io.crdb.docker.RemoteClientApplication.handleProcess(RemoteClientApplication.java:141) ~[classes/:21.0.0-SNAPSHOT]

at io.crdb.docker.RemoteClientApplication.run(RemoteClientApplication.java:84) ~[classes/:21.0.0-SNAPSHOT]

at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:782) ~[spring-boot-2.5.2.jar:2.5.2]

... 13 common frames omitted

Caused by: java.io.IOException: error=0, Failed to exec spawn helper: pid: 29, exit value: 1

at java.base/java.lang.ProcessImpl.forkAndExec(Native Method) ~[na:na]

at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:313) ~[na:na]

at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244) ~[na:na]

at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109) ~[na:na]

... 17 common frames omitted```

**Comment by xzyfer** [comment]
@vbabenkoru out of curiosity are you using an M1 mac?

**Comment by grantas33** [comment]
I'm getting the same error on ARM64 M1 Mac, I think the fact that the image is for amd64 is the issue
